### ISSUE TITLE
bag in css

### ISSUE THREAD

**Issue by Wolf-Den1994** [ViktoryiaYatskova/code-quality-principles#1]
открыв файлы, первое что бросилось в глаза, ошибка в style.css красного цвета. из-за отсутствия точки с запятой.
![image](https://user-images.githubusercontent.com/68957176/111913648-25d38c00-8a80-11eb-90ea-1c85034bd23c.png)
следовательно если исправить ошибку, то визуально приложение меняется, т.к. перечеркивает выполненную задачу
![image](https://user-images.githubusercontent.com/68957176/111918097-88368780-8a94-11eb-9dbb-e6bf41bdc266.png)
отсюда следствие, может следует обновить в задании картинку, в которой выполненные задачи не перечеркнуты?

**Comment by ViktoryiaYatskova** [comment]
Спасибо. 😊 Резонно.

**Comment by ViktoryiaYatskova** [comment]
https://github.com/rolling-scopes-school/stage0/pull/30/commits/003824c26339d3ce0e6435e9fd38b1bd4323926c
