### ISSUE TITLE
HTML formatting

### ISSUE THREAD

**Issue by Wolf-Den1994** [ViktoryiaYatskova/code-quality-principles#2]
1.Форматирование
если выдавать студентам, то лучше всё же написать что тут нужен span 
![image](https://user-images.githubusercontent.com/68957176/111918701-71ddfb00-8a97-11eb-8a3c-6f559879431a.png)
и должно быть что то вроде такого:
![image](https://user-images.githubusercontent.com/68957176/111919768-b4560680-8a9c-11eb-8c1c-0b5b0023de19.png)
а то чувствую студенты понапроверяют работ и будут скандалить на кросс-чеке

**Comment by ViktoryiaYatskova** [comment]
Не уверена. Вполне реальный пример на проекте, почему <span> здесь обязателен? К тому же в задании такого примера нет.

**Comment by Wolf-Den1994** [comment]
Есть верхний пример. Но раз это правильно, тогда думаю, что ложное замечание )
