### ISSUE TITLE
need flex or more width

### ISSUE THREAD

**Issue by Wolf-Den1994** [ViktoryiaYatskova/code-quality-principles#3]
если выровнять все блоки в html, то появляются пробелы между блоками input и button. из-за чего плывет приложение.
![image](https://user-images.githubusercontent.com/68957176/111953639-f3657580-8af7-11eb-8064-726478e82306.png)
фиксится одним из двух а можно и сразу двумя вариантами: 
1. увеличением ширины у блока <div class="centered-main-page-element">  установлено width: 400px; можно поднять хотя бы на 15px , а лучше на 25px.
2. задание все тегам li свойств
  display: flex;
  justify-content: space-between;
  align-items: center;

оба варианта лучше использовать вместе. т.к. если использовать только первый вариант, то элементы расположены немного криво
![image](https://user-images.githubusercontent.com/68957176/111954112-a8982d80-8af8-11eb-97b3-a54873cbd58b.png)

**Comment by ViktoryiaYatskova** [comment]
Что-то пошло не так при выравнивании. Похоже, что лишние пробелы попали ВНУТРЬ тегов, этого быть не должно. Или же есть trailing spaces. Я бы проверила измения с форматированием

**Comment by ViktoryiaYatskova** [comment]
@Wolf-Den1994, перепроверь пожалуйста свои изменения. Я не воспроизвела у себя проблемы

**Comment by Wolf-Den1994** [comment]
Вернул исходную ширину 400px и убрал флексы. Проблема снова появилась 
![image](https://user-images.githubusercontent.com/68957176/112177378-e9cc3280-8c09-11eb-99d4-312e2bdd6fb5.png)
Лишних пробелов не вижу, только перед тегами. После тегов и внутри лишних пробелов нет.
![image](https://user-images.githubusercontent.com/68957176/112177767-44658e80-8c0a-11eb-9389-40eeb7926627.png)
Если в html склеить всё вместе, то проблема исчезает.
![image](https://user-images.githubusercontent.com/68957176/112177873-5ba47c00-8c0a-11eb-8059-90a97cde283b.png)
Я конечно, когда то читал про экранирование пробелов за тегом, потому что они могут показаться в браузере, но я думаю, что это уже не будет чистым кодом )
![image](https://user-images.githubusercontent.com/68957176/112178294-b211ba80-8c0a-11eb-97b1-a8cc8e372f98.png)
Возможно тогда сделать пометку в задании в пункте критерии оценки?
"Ширина приложения может быть увеличена или уменьшена. Ширину приложения не проверяется и не оценивается."
P.S. пока что в чате эта проблема не была обнаружена не у кого.

**Comment by Wolf-Den1994** [comment]
Всё дело в блочно-строчных элементах, вот статья https://htmlacademy.ru/blog/boost/frontend/fighting-the-space-between-inline-block-elements

**Comment by Wolf-Den1994** [comment]
Проблема не только у меня как минимум уже, обнаружил еще одного человека с данной проблемой.
![image](https://user-images.githubusercontent.com/68957176/112180300-7d9efe00-8c0c-11eb-81aa-9b5447474911.png)

**Comment by ViktoryiaYatskova** [comment]
https://github.com/ViktoryiaYatskova/clean-code-s1e1/commit/a38cd58a90e13a16d65c035d098b68cea2baa772

**Comment by ViktoryiaYatskova** [comment]
Спасибо!
