### ISSUE TITLE
bem

### ISSUE THREAD

**Issue by Wolf-Den1994** [ViktoryiaYatskova/code-quality-principles#4]
в продвинутом задании предлагается использовать БЭМ
если просто как дополнить html, то ничего не ломается, но если необходимо дописать в css (а видимо так и есть из задания), то всё ламается, после добавления нового элемента, т.к. добавляется элемент li у которого нет класса вообще
![image](https://user-images.githubusercontent.com/68957176/111954481-38d67280-8af9-11eb-9ff5-ed3e261d34f1.png)
может как следствие писать БЭМ только в html или нужно переделывать, дописывать js . хотя в задании написано что рефакторинг делать в html и css

**Comment by ViktoryiaYatskova** [comment]
Добавила предупреждение в текст задания:
https://github.com/rolling-scopes-school/stage0/pull/30/commits/59a46b0ff06a492d5b2b7b1dab4b7f85c4ef9a13
