### ISSUE TITLE
Cross-check list

### ISSUE THREAD

**Issue by Nata-Roma** [ViktoryiaYatskova/code-quality-principles#5]
Вопрос по проверке cross-check review.

В форме первый пункт звучит так:
"Отступы' из html-and-css выполняется во всем проекте: табуляция не используется, все отступы выполнены пробельным символом".

Каким образом можно проверить в браузере (Page Source), пробел это или табуляция?

В форме также есть такой пункт:
"Правило '2.1 БЭМ' из html-and-css-extended соблюдено: все id и классы именованы согласно БЭМ нотации".

Разве у БЭМа есть правила для именования идентификаторов id?

**Comment by ViktoryiaYatskova** [comment]
Проверять нужно не в браузере, а в IDE.

> Разве у БЭМа есть правила для именования идентификаторов id?
Тут действительно недочет. Поправлю.

**Comment by ViktoryiaYatskova** [comment]
https://github.com/rolling-scopes-school/checklist/pull/21
