### ISSUE TITLE
Items of checklist

### ISSUE THREAD

**Issue by Rasskris** [ViktoryiaYatskova/code-quality-principles#6]
## В требованиях к заданию прописано следующее: 

<img width="600" alt="Снимок экрана 2021-03-22 в 16 52 18" src="https://user-images.githubusercontent.com/62946911/112000628-38f16500-8b2f-11eb-86f2-a52f9f5a07f8.png">

## Но тут получается немного путаница, что выполнив один коммит на один пункт из чек-листа, я могу выполнить этот пункт
<img width="600" alt="Снимок экрана 2021-03-22 в 16 53 44" src="https://user-images.githubusercontent.com/62946911/112000647-3ee74600-8b2f-11eb-8eaf-6b033b57c0f7.png">

## и этот тоже
<img width="600" alt="Снимок экрана 2021-03-22 в 16 53 54" src="https://user-images.githubusercontent.com/62946911/112000663-427acd00-8b2f-11eb-8a54-b06230bba54f.png">

**Comment by ViktoryiaYatskova** [comment]
1.1 Исключает использование tab-ов для отступов (тут ищем tab-ы и заменяем на пробелы, если найдутся) 
2.1 Говорит о том, что отступы должны быть в принципе (тут расставляем отступы, если их нет)
